interface Route {
  path: string;
  title: string;
  description: string;
  keywords: string[];
  searchTerms: string[];
  icon?: string;
  category: "ana" | "görevler" | "raporlar" | "yönetim" | "hesap";
}

export const routes: Route[] = [
  {
    path: "/dashboard",
    title: "Dashboard",
    description: "Ana sayfa ve genel bakış",
    category: "ana",
    icon: "home",
    keywords: ["dashboard", "ana sayfa", "özet", "genel bakış", "panel"],
    searchTerms: [
      "dashboard",
      "ana sayfa",
      "özet",
      "genel bakış",
      "panel",
      "anasayfa",
      "kontrol paneli",
      "gösterge paneli",
      "başlangıç",
      "giriş sayfası",
      "ana ekran",
      "genel durum",
    ],
  },
  {
    path: "/tasks",
    title: "Görevler",
    description: "Görevlerinizi yönetin",
    category: "görevler",
    icon: "check-square",
    keywords: ["görevler", "yapılacaklar", "todo", "task", "iş"],
    searchTerms: [
      "görevler",
      "yapılacaklar",
      "todo",
      "task",
      "iş",
      "görev listesi",
      "yapılacak işler",
      "görev yönetimi",
      "iş takibi",
      "görev takibi",
      "yapılacaklar listesi",
      "görev oluştur",
      "yeni görev",
      "görev düzenle",
      "görev sil",
      "görev detayı",
      "görev durumu",
    ],
  },
  {
    path: "/reports",
    title: "Raporlar",
    description: "Raporlarınızı görüntüleyin ve yönetin",
    category: "raporlar",
    icon: "file-text",
    keywords: ["raporlar", "rapor", "belge", "döküman", "report"],
    searchTerms: [
      "raporlar",
      "rapor",
      "belge",
      "döküman",
      "report",
      "rapor listesi",
      "rapor oluştur",
      "yeni rapor",
      "rapor düzenle",
      "rapor sil",
      "rapor detayı",
      "rapor durumu",
      "rapor yönetimi",
      "rapor görüntüle",
      "raporlama",
      "analiz",
      "istatistik",
      "özet rapor",
      "detaylı rapor",
      "haftalık rapor",
      "aylık rapor",
      "yıllık rapor",
      "proje raporu",
    ],
  },
  {
    path: "/calendar",
    title: "Takvim",
    description: "Takvim görünümü ve planlamalar",
    category: "görevler",
    icon: "calendar",
    keywords: ["takvim", "calendar", "plan", "program", "ajanda"],
    searchTerms: [
      "takvim",
      "calendar",
      "plan",
      "program",
      "ajanda",
      "etkinlikler",
      "toplantılar",
      "randevular",
      "planlamalar",
      "takvim görünümü",
      "günlük görünüm",
      "haftalık görünüm",
      "aylık görünüm",
      "etkinlik ekle",
      "toplantı planla",
      "randevu oluştur",
    ],
  },
  {
    path: "/organizations",
    title: "Organizasyonlar",
    description: "Organizasyonlarınızı yönetin",
    category: "yönetim",
    icon: "briefcase",
    keywords: ["organizasyonlar", "şirket", "kurum", "organization"],
    searchTerms: [
      "organizasyonlar",
      "şirket",
      "kurum",
      "organization",
      "firma",
      "organizasyon yönetimi",
      "şirket yönetimi",
      "kurum yönetimi",
      "organizasyon ekle",
      "şirket ekle",
      "kurum ekle",
      "organizasyon düzenle",
      "şirket düzenle",
      "kurum düzenle",
      "organizasyon detayı",
      "şirket bilgileri",
      "kurum bilgileri",
    ],
  },
  {
    path: "/invitations",
    title: "Davetiyeler",
    description: "Davetiye isteklerini yönetin",
    category: "yönetim",
    icon: "mail",
    keywords: ["davetiyeler", "davet", "invitation", "istek"],
    searchTerms: [
      "davetiyeler",
      "davet",
      "invitation",
      "istek",
      "davetiye yönetimi",
      "davet gönder",
      "davetiye gönder",
      "davet oluştur",
      "davetiye oluştur",
      "davet listesi",
      "davetiye listesi",
      "bekleyen davetler",
      "gelen davetler",
      "giden davetler",
      "davet durumu",
      "davetiye durumu",
    ],
  },
  {
    path: "/profile",
    title: "Profil",
    description: "Profil bilgilerinizi düzenleyin",
    category: "hesap",
    icon: "user",
    keywords: ["profil", "hesap", "kullanıcı", "profile", "account"],
    searchTerms: [
      "profil",
      "hesap",
      "kullanıcı",
      "profile",
      "account",
      "profil bilgileri",
      "hesap bilgileri",
      "kullanıcı bilgileri",
      "profil düzenle",
      "hesap düzenle",
      "kullanıcı düzenle",
      "şifre değiştir",
      "profil fotoğrafı",
      "kişisel bilgiler",
      "iletişim bilgileri",
      "hesap ayarları",
    ],
  },
  {
    path: "/settings",
    title: "Ayarlar",
    description: "Uygulama ayarlarını özelleştirin",
    category: "hesap",
    icon: "settings",
    keywords: ["ayarlar", "tercihler", "settings", "preferences"],
    searchTerms: [
      "ayarlar",
      "tercihler",
      "settings",
      "preferences",
      "uygulama ayarları",
      "sistem ayarları",
      "genel ayarlar",
      "bildirim ayarları",
      "tema ayarları",
      "dil ayarları",
      "güvenlik ayarları",
      "gizlilik ayarları",
      "hesap ayarları",
      "kullanıcı ayarları",
      "özelleştirme",
    ],
  },
];
